pom.xml
src/main/java/com/odysseusinc/arachne/datanode/config/SwaggerConfig.java
src/main/java/com/odysseusinc/arachne/datanode/controller/AchillesController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/AuthController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/BuildNumberController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/DataNodeController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/DataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/UserController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/admin/AdminController.java

ARACHNE-1500 Refactored swagger config and dependecies has been moved

---

src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java

ARACHNE-1524

---

src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/service/DataSourceService.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataSourceServiceImpl.java

Arachne 1525

---

src/main/java/com/odysseusinc/arachne/datanode/service/impl/UserServiceImpl.java

ARACHNE-993

---

src/main/java/com/odysseusinc/arachne/datanode/controller/DataNodeController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/ExceptionHandlingAdvice.java
src/main/java/com/odysseusinc/arachne/datanode/controller/ExceptionHandlingController.java
src/main/resources/application-dev.yml
src/test/resources/config/application.yml

add atlas props to test profile

refactored back-end validation

---

src/main/java/com/odysseusinc/arachne/datanode/controller/AchillesController.java
src/main/java/com/odysseusinc/arachne/datanode/service/AchillesService.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AchillesServiceImpl.java

start Achilles job after creation for front sync

ARACHNE-1567

---

src/main/resources/application-base.yml

ARACHNE-1538

---

src/main/java/com/odysseusinc/arachne/datanode/Constants.java
src/main/java/com/odysseusinc/arachne/datanode/controller/AchillesController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/AuthController.java
src/main/java/com/odysseusinc/arachne/datanode/service/BaseCentralIntegrationService.java
src/main/java/com/odysseusinc/arachne/datanode/service/UserService.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/BaseCentralIntegrationServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/UserServiceImpl.java

ARACHNE-1627

---

src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java

ARACHNE-1663

---

src/main/java/com/odysseusinc/arachne/datanode/Constants.java
src/main/java/com/odysseusinc/arachne/datanode/config/IntegrationConfig.java
src/main/java/com/odysseusinc/arachne/datanode/controller/admin/BaseAdminController.java
src/main/java/com/odysseusinc/arachne/datanode/service/AtlasService.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/AtlasClient.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/AtlasClientConfig.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/AtlasLoginClient.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AtlasServiceImpl.java
src/main/resources/application-base.yml

add atlas check connection rest

Arachne 1649

---

src/test/java/com/odysseusinc/arachne/datanode/TestApplication.java

ARACHNE-1649

---

pom.xml

Update modelmapper version to fix config issue

ARACHNE-1889 Determine CDM version automatically

---

src/main/java/com/odysseusinc/arachne/datanode/dto/converters/DataSourceToDataSourceDTOConverter.java
src/main/resources/application-base.yml
src/main/resources/db/migration/V20180214172623__system_settings_modifying.sql
src/test/resources/application.properties

ARACHNE-1950 Added default values for target_schema, result_schema

---

src/main/java/com/odysseusinc/arachne/datanode/config/IntegrationConfig.java
src/main/java/com/odysseusinc/arachne/datanode/config/WebSecurityConfig.java
src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/model/atlas/Atlas.java
src/main/java/com/odysseusinc/arachne/datanode/model/datasource/DataSource.java
src/main/java/com/odysseusinc/arachne/datanode/repository/DataSourceRepository.java
src/main/java/com/odysseusinc/arachne/datanode/service/DataSourceService.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/ArachneHttpClientBuilder.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/portal/CentralClientConfig.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AtlasServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataSourceServiceImpl.java
src/main/resources/application-base.yml
src/test/resources/application.properties

Arachne 2289

---

src/test/java/com/odysseusinc/arachne/datanode/controller/AchillesControllerTest.java
src/test/java/com/odysseusinc/arachne/datanode/service/CohortServiceTest.java

(cherry picked from commit 8ef4a84)

ARACHNE-2396 - Tests

---

src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/dto/datasource/CreateDataSourceDTO.java

fixed parameters of add method

ARACHNE-2489 create ds

---

pom.xml
src/test/java/com/odysseusinc/arachne/datanode/service/CohortServiceTest.java

fixes failed test

---

src/main/java/com/odysseusinc/arachne/datanode/controller/AuthController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/ExceptionHandlingAdvice.java

(cherry picked from commit a46468d)

ARACHNE-2540 - Fixed error message when external system is not available

---

src/main/java/com/odysseusinc/arachne/datanode/service/impl/AtlasServiceImpl.java

(cherry picked from commit 92de367)

ARACHNE-2569 - Fixed working with atlasClientPool

---

src/main/java/com/odysseusinc/arachne/datanode/dto/serialize/MultiFormatDateDeserializer.java

(cherry picked from commit 58ac04c)

Arachne 2557

---

src/main/java/com/odysseusinc/arachne/datanode/dto/serialize/MultiFormatDateDeserializer.java

(cherry picked from commit 58ac04c)

ARACHNE-2557. Cohort / IR execution imported from ATLAS fails (#262)

---

src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/dto/converters/CreateDataSourceDTOToDataSourceConverter.java
src/main/java/com/odysseusinc/arachne/datanode/dto/converters/DataSourceToDataSourceDTOConverter.java
src/main/java/com/odysseusinc/arachne/datanode/dto/converters/DataSourceToDataSourceUnsecuredDTOConverter.java
src/main/java/com/odysseusinc/arachne/datanode/dto/datasource/CreateDataSourceDTO.java
src/main/java/com/odysseusinc/arachne/datanode/model/datasource/DataSource.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataSourceServiceImpl.java

Adds Support of BQ keyfile json for authentication of EE jobs

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/Constants.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/AchillesProcessors.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/ConditionEraReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/ConditionReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/DataDensityReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/DeathReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/DrugEraReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/DrugReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/MeasurementReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/ObservationPeriodReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/ObservationReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/PersonReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/ProcedureReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/achilles/VisitReport.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AchillesServiceImpl.java

Broken Achilles-Hill and Person reports after Achilles result import, compilation warnings, code clean-up

arachne-ui-issue-651 import reports issues

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/config/HandlebarsConfig.java

Resolves OHDSI/ArachneCommons#181

conforms arachne-commons structure changes

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/config/HandlebarsConfig.java
src/main/java/com/odysseusinc/arachne/datanode/dto/datasource/DataSourceBusinessDTO.java
src/main/java/com/odysseusinc/arachne/datanode/model/datasource/AutoDetectedFields.java

resolves OHDSI/ArachneCommons#181

Fixes imports conforming commons optimization

---

src/main/java/com/odysseusinc/arachne/datanode/controller/AuthController.java

Use the central token for communication to CentralAPI
Closes #321

Fixes failed signature validation

---

src/test/resources/application.properties

add default value for the submission.result.files.exclusions property

submission.result.files.exclusions test property value

---

src/main/resources/application-base.yml
src/main/resources/application-dev.yml

add execution engine connection properties

add execution engine connection properties

---

src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/ExceptionHandlingAdvice.java
src/main/java/com/odysseusinc/arachne/datanode/util/LogUtils.java

Fixes Datanode shows info in Sources list inconsistent with Central

---

src/main/java/com/odysseusinc/arachne/datanode/service/impl/BaseCentralIntegrationServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataSourceServiceImpl.java

Fixes Failing of DataSource update in Network mode

---

src/main/java/com/odysseusinc/arachne/datanode/config/WebSecurityConfig.java
src/main/java/com/odysseusinc/arachne/datanode/security/AuthenticationTokenFilter.java

Fixes Build number is not loaded in some cases

---

src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataNodeServiceImpl.java
src/test/java/com/odysseusinc/arachne/datanode/TestApplication.java
src/test/resources/application.properties

fixes tests

---

src/main/java/com/odysseusinc/arachne/datanode/service/messaging/BaseAtlas2_7Mapper.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/IncidenceRatesRequestHandler.java

Fixes OHDSI/ArachneCentralAPI#624

fixes Error analysis import

---

src/main/java/com/odysseusinc/arachne/datanode/service/messaging/BaseRequestHandler.java

Removes illegal symbols from cohort files

adds sanitation for cohort files

---

src/main/java/com/odysseusinc/arachne/datanode/controller/analysis/AnalysisController.java

Hides Heracles and Pathways until they would be fully implemented or fixed

hides Heracles and Pathways analyses from submissions

---

src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/dto/converters/DataSourceToDataSourceUnsecuredDTOConverter.java
src/main/java/com/odysseusinc/arachne/datanode/dto/datasource/CreateDataSourceDTO.java
src/main/java/com/odysseusinc/arachne/datanode/dto/datasource/validation/BaseValidator.java
src/main/java/com/odysseusinc/arachne/datanode/dto/datasource/validation/CreateDataSourceCredentialsValidator.java
src/main/java/com/odysseusinc/arachne/datanode/dto/datasource/validation/DataSourceCredentialsValidator.java
src/main/java/com/odysseusinc/arachne/datanode/dto/datasource/validation/ValidCredentials.java
src/main/java/com/odysseusinc/arachne/datanode/model/datasource/DataSource.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataSourceServiceImpl.java

Related to OHDSI/ArachneUI#696

fixes BigQuery datasource create/edit

---

src/main/resources/application-base.yml

Enable Cohort counts setting by default

Enable Cohort counts setting by default

---

src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataSourceServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataSourceUUIDMigration.java

Fixes the following:
1. UUID migration should not start in the Stand-alone mode

Migration should not run in standalone mode

---

pom.xml

set 0.0.2-QA version of Authenticator

set 0.0.2-QA version of Authenticator

---

src/main/java/com/odysseusinc/arachne/datanode/service/messaging/PathwayRequestHandler.java

parallel modifications of the code base cause compilation failure

fix broken build

---

src/main/resources/db/migration/V20190708193000__fix-analysis-forighn-keys.sql

ARACHNE-2759 Errors during prod Upgrade

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/config/DataSourceConfig.java
src/main/java/com/odysseusinc/arachne/datanode/model/types/CheckedEncryptedStringType.java

Update vulnerable and some other dependencies

Update vulnerable and some other dependencies

---

src/main/java/com/odysseusinc/arachne/datanode/service/AnalysisInfoBuilder.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/portal/CentralSystemClient.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AnalysisInfoBuilderImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/BaseAtlas2_7Mapper.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/CohortCharacterizationRequestHandler.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/CohortHeraclesRequestHandler.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/EstimationRequestHandler.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/IncidenceRatesRequestHandler.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/LegacyCohortRequestHandler.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/PathwayRequestHandler.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/PatientLevelPredictionRequestHandler.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/estimation/EstimationAtlas2_7Mapper.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/prediction/PredictionAtlas2_7Mapper.java

generate analysis description field during import

Analysis import

---

src/main/java/com/odysseusinc/arachne/datanode/config/WebSecurityConfig.java
src/main/java/com/odysseusinc/arachne/datanode/controller/AuthController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/security/AuthenticationTokenFilter.java
src/main/java/com/odysseusinc/arachne/datanode/service/AuthenticationService.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/portal/CentralRequestInterceptor.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AuthenticationServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/UserServiceImpl.java
src/main/resources/application-base.yml
src/test/java/com/odysseusinc/arachne/datanode/config/CentralIntegrationServiceTestConfig.java
src/test/resources/config/application.yml

ARACHNE-2729 Add IAP auth support into Standalone Node

ARACHNE-2729 Add IAP auth support into Standalone Node

---

src/main/java/com/odysseusinc/arachne/datanode/config/WebSecurityConfig.java
src/main/java/com/odysseusinc/arachne/datanode/controller/AuthController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java
src/main/java/com/odysseusinc/arachne/datanode/security/AuthenticationTokenFilter.java
src/main/java/com/odysseusinc/arachne/datanode/service/AuthenticationService.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/portal/CentralRequestInterceptor.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AuthenticationServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/UserServiceImpl.java
src/main/resources/application-base.yml

Qa 1.16.0 fix

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/Constants.java
src/main/java/com/odysseusinc/arachne/datanode/controller/AtlasController.java
src/main/java/com/odysseusinc/arachne/datanode/dto/atlas/AtlasDetailedDTO.java
src/main/java/com/odysseusinc/arachne/datanode/dto/converters/AtlasDetailedDTOToAtlasConverter.java
src/main/java/com/odysseusinc/arachne/datanode/dto/converters/BaseAtlasToAtlasDetailedDTOConverter.java
src/main/java/com/odysseusinc/arachne/datanode/model/atlas/Atlas.java
src/main/java/com/odysseusinc/arachne/datanode/service/AtlasService.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/AtlasAuthRequestInterceptor.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/AtlasAuthSchema.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/AtlasAuthentication.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AtlasServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/util/DataSourceUtils.java
src/main/resources/db/migration/V20200421180027__add-atlas-token.sql

implements Atlas oauth token authentication

---

pom.xml

upgrade sqlRender version

---

src/main/resources/application-base.yml

fix proxy properties

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/Constants.java
src/main/java/com/odysseusinc/arachne/datanode/config/HibernateValidatorJpaConfig.java
src/main/java/com/odysseusinc/arachne/datanode/config/ValidatorConfig.java
src/main/java/com/odysseusinc/arachne/datanode/controller/AtlasController.java
src/main/java/com/odysseusinc/arachne/datanode/dto/atlas/AtlasDetailedDTO.java
src/main/java/com/odysseusinc/arachne/datanode/dto/converters/AtlasDetailedDTOToAtlasConverter.java
src/main/java/com/odysseusinc/arachne/datanode/dto/converters/BaseAtlasToAtlasDetailedDTOConverter.java
src/main/java/com/odysseusinc/arachne/datanode/model/atlas/Atlas.java
src/main/java/com/odysseusinc/arachne/datanode/model/datanode/DataNode.java
src/main/java/com/odysseusinc/arachne/datanode/model/datanode/validation/DataNodeTokenValidator.java
src/main/java/com/odysseusinc/arachne/datanode/model/datanode/validation/NonEmptyToken.java
src/main/java/com/odysseusinc/arachne/datanode/service/AtlasService.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/AtlasAuthRequestInterceptor.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/AtlasAuthentication.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AtlasServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataSourceUUIDMigration.java
src/main/java/com/odysseusinc/arachne/datanode/util/DataSourceUtils.java
src/main/resources/application-base.yml
src/main/resources/db/migration/V20191016155451__remove_dn-token_constraint.sql
src/main/resources/db/migration/V20200421180027__add-atlas-token.sql
src/test/java/com/odysseusinc/arachne/datanode/service/Const.java
src/test/java/com/odysseusinc/arachne/datanode/service/DataNodeServiceNetworkTest.java
src/test/java/com/odysseusinc/arachne/datanode/service/DataNodeServiceStandaloneTest.java
src/test/resources/data/dataset/empty-datanode.xml
src/test/resources/data/dataset/users.xml

Update codebase version to 1.16.1

Update codebase version to 1.16.1

---

pom.xml

remove duplications

---

src/main/resources/application-base.yml

upload submission: exceeds the configured maximum [ARACHNE-2818]

---

src/main/resources/application-base.yml

Upload limits

---

src/main/resources/application-base.yml

fix config value

---

src/main/resources/application-base.yml

fix max-file-size property

---

README.md
pom.xml

update version to 1.16.2-snapshot

update version to 1.16.2-snapshot

---

src/main/java/com/odysseusinc/arachne/datanode/security/AuthenticationTokenFilter.java

Fixes https://odysseusdataservices.atlassian.net/browse/ARACHNE-2772
Log authentication exception only for debug mode

ARACHNE-2772 token invalid Error message floods into log

---

src/main/java/com/odysseusinc/arachne/datanode/service/messaging/CohortCharacterizationRequestHandler.java

update Cohort Characterization skeleton

update Cohort Characterization skeleton

---

src/main/java/com/odysseusinc/arachne/datanode/service/CohortNamePatcher.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/CohortNamePatcherImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/CohortCharacterizationRequestHandler.java
src/test/java/com/odysseusinc/arachne/datanode/service/impl/CohortNamePatcherImplTest.java
src/test/resources/com/odysseusinc/arachne/datanode/service/StudyWithIncorrectCohortName.json
src/test/resources/com/odysseusinc/arachne/datanode/service/StudyWithIncorrectJSON.json

patch Cohort names on import

---

src/main/java/com/odysseusinc/arachne/datanode/service/messaging/CohortCharacterizationRequestHandler.java

Fix CC results reports

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/service/CohortNamePatcher.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/CohortNamePatcherImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/CohortCharacterizationRequestHandler.java

Init 1.16.3

---

src/main/resources/heracles/main.r

Full Heracles analysis with drilldown details in zip parts

Full Heracles analysis with dropdown details in zip parts

---

pom.xml

Update redshift driver to version 1.2.43.1067

redshift driver update

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/EstimationRequestHandler.java
src/main/resources/estimation/runAnalysis.R

update hydra to v0.1.0 which supports Andromeda

update skeleton and wrapper which uses Andromeda library

---

src/main/resources/heracles/main.r

Heracles treemap drill down reports optimizations

heracles treemap drilldown reports optimizations

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/scheduler/CohortScheduler.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/ArachneHttpClientBuilder.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/atlas/TokenDecoder.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AtlasClientServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/messaging/CommonAnalysisRequestHandler.java
src/main/resources/application-base.yml

Atlas import improvements

---

src/main/resources/plp/runAnalysis.R

ARACHNE-2907 PLP result does not contain ShinyApp directory

---

pom.xml

Update to version-1.17.0

---

README.md
pom.xml
src/main/java/com/odysseusinc/arachne/datanode/service/client/ArachneHttpClientBuilder.java

ARACHNE-2901 add support for the latest java 8 version

ARACHNE-2901 support the latest java 8 version

---

src/main/java/com/odysseusinc/arachne/datanode/Constants.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AnalysisResultsServiceImpl.java

Fail analysis if errorReportR.txt exists

Fail analysis if errorReportR.txt exists

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/config/DockerConfig.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AchillesServiceImpl.java

Fix Achilles docker integration
Closes #457

Fix Achilles docker integration

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/service/impl/AnalysisResultsServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/BaseAnalysisServiceImpl.java

jackson-databind version update

jackson-databind version update

---

pom.xml

update to the patch version jackson-databind:2.7.5.1

jackson-databind:2.7.5.1

---

pom.xml
src/main/docker/Dockerfile

update datanode docker image to the ubuntu 20 base

---

pom.xml

switch docker images to the new odyssues hub

switch docker images to the new odyssues hub

---

src/main/java/com/odysseusinc/arachne/datanode/repository/UserRepository.java
src/main/java/com/odysseusinc/arachne/datanode/scheduler/CentralScheduler.java
src/main/java/com/odysseusinc/arachne/datanode/service/BaseCentralIntegrationService.java
src/main/java/com/odysseusinc/arachne/datanode/service/DataNodeService.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/BaseCentralIntegrationServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/DataNodeServiceImpl.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/UserServiceImpl.java
src/test/java/com/odysseusinc/arachne/datanode/service/DataNodeServiceNetworkTest.java
src/test/java/com/odysseusinc/arachne/datanode/service/DataNodeServiceStandaloneTest.java
src/test/java/com/odysseusinc/arachne/datanode/service/impl/CentralIntegrationServiceImplTest.java

linking users after datanode registration

network mode users linking

---

src/main/java/com/odysseusinc/arachne/datanode/repository/UserRepository.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/UserServiceImpl.java
src/main/resources/db/migration/V20210224150500__unique_username.sql
src/test/resources/application.properties

case insensitive Login

---

pom.xml
src/main/java/com/odysseusinc/arachne/datanode/service/client/decoders/ByteArrayDecoder.java
src/main/resources/application-base.yml
src/test/resources/application.properties

clean up datanode configs, small optimizations

clean up datanode configs, small optimizations

---

src/main/resources/heracles/main.r

fixes https://github.com/OHDSI/ArachneCentralAPI/issues/752

Removed heracles heel report from heracles analysis

---

src/main/java/com/odysseusinc/arachne/datanode/controller/admin/AdminController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/admin/BaseAdminController.java
src/main/java/com/odysseusinc/arachne/datanode/service/ExecutionEngineIntegrationService.java
src/main/java/com/odysseusinc/arachne/datanode/service/ExecutionEngineStatus.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/engine/EngineClient.java
src/main/java/com/odysseusinc/arachne/datanode/service/client/engine/EngineClientConfig.java
src/main/java/com/odysseusinc/arachne/datanode/service/impl/ExecutionEngineIntegrationServiceImpl.java

Added service for retrieving execution engine status

---

src/main/java/com/odysseusinc/arachne/datanode/controller/analysis/AnalysisController.java

Result file name now has the following template "[prefix-analysis-type]-a[analysis-id]-results.zip"

---

src/main/java/com/odysseusinc/arachne/datanode/controller/AuthController.java
src/main/java/com/odysseusinc/arachne/datanode/controller/analysis/AnalysisController.java
src/main/java/com/odysseusinc/arachne/datanode/security/AuthenticationTokenFilter.java

Also store authentication token in cookie as well to allow downloading files directly, without file-saver.js

Content-Disposition header for downloading result files

---

src/main/resources/estimation/runAnalysis.R

- https://github.com/OHDSI/WebAPI/pull/1928
- https://github.com/OHDSI/WebAPI/commit/b0433d2f2fa5ba98b970e067050dd0fde1ee2911

PLE analysis entry point changes for multi-threaded execution
